---
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

# Fail2Ban
- name: Include Fail2Ban tasks
  ansible.builtin.include_tasks: fail2ban.yml
  when: security_fail2ban_enabled | bool

# SSH
- name: Include SSH tasks
  ansible.builtin.include_tasks: ssh.yml

# Autoupdate
- name: Include Autoupdate tasks for RedHat
  ansible.builtin.include_tasks: autoupdate-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'
    - security_autoupdate_enabled | bool

- name: Include Autoupdate tasks for Debian
  ansible.builtin.include_tasks: autoupdate-Debian.yml
  when:
    - ansible_os_family == 'Debian'
    - security_autoupdate_enabled | bool
